spring:
  datasource:
    url: jdbc:mysql://db:3306/coupons?useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    schema: classpath:import.sql
    data: classpath:data.sql
    initialize: false
  jpa:
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  redis:
    host: redis
    port: 6379
#    username: root
#    password: root
server:
  port: 7777

